### ISSUE TITLE
Testing for Static Version of Download Page

### ISSUE THREAD

**Issue by AlanBreck** [brave/qa-resources#171] opened 2020-07-16 21:50 UTC
We are in the process of migrating core pages of brave.com from WordPress to a static website. Given the high priority of the download page, I'd like to request Q/A on the page.

**Test URL:** https://staging.brave.com/download (basic auth credentials found in Websites vault in 1Password)
**Baseline URL:** https://brave.com/download

Please let me know if you need me to put together more formal test cases (guidance on this appreciated), however here are a few areas that would need testing:

- The "Download Brave for ..." should display the appropriate platform for the current device (iOS, Android, Linux, etc)
- The referral code should be appended to the download link if present (NOTE: ref code not appended to direct platform downloads):
  - Step 1: visit https://staging.brave.com/w0ts0n
  - Step 2: navigate to https://staging.brave.com/download
  - Step 3: ensure `WTS071` is appended to download url.
- All download links should work
- Android and iOS links under `Brave for Mobile` section should work properly.

All of the above should be true across all languages:
- https://staging.brave.com/download/
- https://staging.brave.com/ja/download/
- https://staging.brave.com/ko/download/
- https://staging.brave.com/zh/download/
- https://staging.brave.com/de/download/
- https://staging.brave.com/fr/download/

**Comment by LaurenWags** [comment] 2020-07-27 15:39
Verified test plan from https://github.com/brave/qa-resources/issues/171#issue-658601642 for the below OSes/Browsers/Lanaguages:

<details>
<summary>1. **PASS** macOS Mojave 10.14.6 - `en`</summary>

 - used Safari as the browser
 - checked the below for English using staging.brave.com/download
 - Confirmed "Download Brave for..." Button displayed macOS
 - Confirmed clicking on that button downloaded the pkg file with `-WTS071` appended
 - Confirmed direct platform download links (below the button) did not have refcode appended to URL
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
<img width="1096" alt="macOS-English" src="https://user-images.githubusercontent.com/28145373/88560959-c7433480-cffc-11ea-9117-dd766fe5e096.png">

</details>

<details>
<summary>2. **PASS** macOS Mojave 10.14.6 - `fr`</summary>

 - used Safari as the browser
 - checked the below for French using staging.brave.com/fr/download
 - Confirmed "Download Brave for..." Button displayed macOS
 - Confirmed clicking on that button downloaded the pkg file with `-WTS071` appended
 - Confirmed direct platform download links (below the button) did not have refcode appended to URL
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
<img width="1091" alt="macOS-French" src="https://user-images.githubusercontent.com/28145373/88561023-dfb34f00-cffc-11ea-9211-728212c3641a.png">

</details>

<details>
<summary>3. **PASS** Win 10 x64 - `en`</summary>

 - Used Edge as the browser
 - checked the below for English using staging.brave.com/download
 - Confirmed "Download Brave for..." Button displayed Windows 64-bit
 - Confirmed clicking on that button downloaded the exe file with `-WTS071` appended
 - Confirmed direct platform download links (below the button) did not have refcode appended to URL
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
<img width="1299" alt="Win10x64-English" src="https://user-images.githubusercontent.com/28145373/88561078-f3f74c00-cffc-11ea-8528-0df66d9e73d5.png">

</details>

<details>
<summary>4. **FAIL** Win 10 x64 - `de`</summary>

 - Used Edge as the browser
 - checked the below for German using staging.brave.com/de/download
 - **FAIL** "Download Brave for..." Button displayed Windows 32-bit not 64-bit
 - **FAIL** Clicking on that button did not download the exe file with `-WTS071` appended - NOTE: page refresh fixes this
 - Confirmed direct platform download links (below the button) did not have refcode appended to URL
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
<img width="1297" alt="Win10x64-German" src="https://user-images.githubusercontent.com/28145373/88561177-11c4b100-cffd-11ea-9b58-7c4eeeaf55b5.png">

</details>

<details>
<summary>5. **PASS** Win 10 x86 - `en`</summary>

 - Used FF as the browser
 - checked the below for English using staging.brave.com/download
 - Confirmed "Download Brave for..." Button displayed Windows 32-bit
 - Confirmed clicking on that button downloaded the exe file with `-WTS071` appended
 - Confirmed direct platform download links (below the button) did not have refcode appended to URL
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
<img width="1216" alt="Win10x86-English" src="https://user-images.githubusercontent.com/28145373/88561242-2608ae00-cffd-11ea-944c-34304f2f19c8.png">

</details>

<details>
<summary>6. **PASS** Win 10 x86 - `zh`</summary>

 - Used FF as the browser
 - checked the below for `zh` using staging.brave.com/zh/download
 - Confirmed "Download Brave for..." Button displayed Windows 32-bit
 - Confirmed clicking on that button downloaded the exe file with `-WTS071` appended
 - Confirmed direct platform download links (below the button) did not have refcode appended to URL
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
<img width="1212" alt="Win10x86-zh" src="https://user-images.githubusercontent.com/28145373/88561303-37ea5100-cffd-11ea-9ed0-e4139084cbcf.png">

</details>

<details>
<summary>7. **PASS** iPad with iOS12 - `en`</summary>

 - used Safari as the browser
 - checked the below for English using staging.brave.com/download
 - Confirmed "Download Brave for..." Button displayed iOS
 - Confirmed long press on the button showed URL with ref code
 - Confirmed (via long press) direct platform download links (below the button) did not have refcode appended to URL
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
![ios-en](https://user-images.githubusercontent.com/28145373/88561344-489ac700-cffd-11ea-9b76-6a7825119c20.jpeg)

</details>

<details>
<summary>8. **PASS** iPad with iOS12 - `ko`</summary>

 - used Safari as the browser
 - checked the below for `ko` using staging.brave.com/ko/download
 - Confirmed "Download Brave for..." Button displayed iOS
 - Confirmed long press on the button showed URL with ref code
 - Confirmed (via long press) direct platform download links (below the button) did not have refcode appended to URL
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
![ios-ko](https://user-images.githubusercontent.com/28145373/88561407-5b150080-cffd-11ea-8c38-66651a187b8a.jpeg)

</details>

Generally issues observed were:
1. On windows the `64-bit` and `32-bit` text on the buttons seems a bit bolder than other text on the button - https://bravesoftware.slack.com/archives/C0HMF8ETE/p1595853639007500?thread_ts=1594936394.439700&cid=C0HMF8ETE
2. On a language download page on Win 10 x64, the button incorrectly says `32-bit`, it should say `64-bit` - https://bravesoftware.slack.com/archives/C0HMF8ETE/p1595854144008000?thread_ts=1594936394.439700&cid=C0HMF8ETE
3. Sometimes translated download pages aren't appending the ref code without a page refresh - https://bravesoftware.slack.com/archives/C0HMF8ETE/p1595855180008500?thread_ts=1594936394.439700&cid=C0HMF8ETE
4. A portion of https://staging.brave.com/zh/download/ is in English (although this does match the current production page, so maybe not an issue) - https://bravesoftware.slack.com/archives/C0HMF8ETE/p1595857449009200?thread_ts=1594936394.439700&cid=C0HMF8ETE

------

**Comment by AlanBreck** [comment] 2020-07-28 18:21
Thank you again for this, @LaurenWags!

> 1. On windows the 64-bit and 32-bit text on the buttons seems a bit bolder than other text on the button
Looks like an anti-aliasing problem. I'll have to investigate further, but I think it's slight enough to proceed.

> 2. On a language download page on Win 10 x64, the button incorrectly says 32-bit, it should say 64-bit
Found the cause and fixed.

> 3. Sometimes translated download pages aren't appending the ref code without a page refresh
This should be resolved, but would appreciate confirmation with a few more tests.

> 4. A portion of https://staging.brave.com/zh/download/ is in English (although this does match the current production page, so maybe not an issue)
As suspected, this is a known issue, and we don't currently have translations for that section.

**Comment by kjozwiak** [comment] 2020-07-29 06:58
Verified test plan from https://github.com/brave/qa-resources/issues/171#issue-658601642 for the below OSes/Browsers/Locales:

<details>
<summary>Case 1 - **PASSED** using macOS 10.15.6 x64 Catalina - EN</summary>

Browser being used: `MS Edge - 84.0.522.44 (Official build) Beta (64-bit)`

 - ensured that staging.brave.com/download looks correct when using `EN`
 - Confirmed "Download Brave for..." Button displayed `macOS`
 - Confirmed clicking on the download button correctly downloaded the `DMG` file
   - https://brave-browser-downloads.s3.brave.com/latest/Brave-Browser.dmg
 - Confirmed clicking on that download button correctly downloaded the `PKG` file with `WTS071` appended
   - https://referrals.brave.com/latest/Brave-Browser-WTS071.pkg
 - Confirmed direct platform download links (below the main download button) doesn't have referral code appended to the download URL
   - https://referrals.brave.com/latest/BraveBrowserSetup.exe
   - https://referrals.brave.com/latest/BraveBrowserSetup32.exe
   - https://referrals.brave.com/latest/Brave-Browser.pkg
   - https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
   - Clicking on GPS --> https://play.google.com/store/apps/details?id=com.brave.browser&hl=en
   - Clicking on iOS App Store --> https://apps.apple.com/us/app/brave-private-web-browser/id1052879175?mt=8&ign-mpt=uo%3D4

<img width="1096" alt="macOS-English" src="https://user-images.githubusercontent.com/28145373/88560959-c7433480-cffc-11ea-9117-dd766fe5e096.png">
</details>

<details>
<summary>Case 2 - **PASSED** using macOS 10.15.6 x64 Catalina - JA</summary>

Browser being used: `Firefox 79.0 - Release`

 - ensured that staging.brave.com/download looks correct when using `JA`
 - Confirmed "Download Brave for..." Button displayed `macOS`
 - Confirmed clicking on the download button correctly downloaded the `DMG` file
   - https://brave-browser-downloads.s3.brave.com/latest/Brave-Browser.dmg
 - Confirmed clicking on that download button correctly downloaded the `PKG` file with `WTS071` appended
   - https://referrals.brave.com/latest/Brave-Browser-WTS071.pkg
 - Confirmed direct platform download links (below the main download button) doesn't have referral code appended to the download URL
   - https://referrals.brave.com/latest/BraveBrowserSetup.exe
   - https://referrals.brave.com/latest/BraveBrowserSetup32.exe
   - https://referrals.brave.com/latest/Brave-Browser.pkg
   - https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
   - Clicking on GPS --> https://play.google.com/store/apps/details?id=com.brave.browser&hl=en
   - Clickong on iOS App Store --> https://apps.apple.com/us/app/brave-private-web-browser/id1052879175?mt=8&ign-mpt=uo%3D4

<img width="1096" alt="macOS-English" src="https://user-images.githubusercontent.com/28145373/88560959-c7433480-cffc-11ea-9117-dd766fe5e096.png">
</details>

<details>
<summary>Case 3 - **PASSED** using Win 8.1 x64 - EN</summary>

Browser being used: `Chrome - 84.0.4147.105 (Official Build) (64-bit)`

 - ensured that staging.brave.com/download looks correct when using `EN`
 - Confirmed "Download Brave for..." Button displayed `Windows 64-bit`
 - Confirmed clicking on the download button correctly downloaded the `exe` file
   - https://brave-browser-downloads.s3.brave.com/latest/BraveBrowserSetup.exe
 - Confirmed clicking on that download button correctly downloaded the `exe` file with `WTS071` appended
   - https://referrals.brave.com/latest/BraveBrowserSetup-WTS071.exe
 - Confirmed direct platform download links (below the main download button) doesn't have referral code appended to the download URL
   - https://referrals.brave.com/latest/BraveBrowserSetup.exe
   - https://referrals.brave.com/latest/BraveBrowserSetup32.exe
   - https://referrals.brave.com/latest/Brave-Browser.pkg
   - https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
   - Clicking on GPS --> https://play.google.com/store/apps/details?id=com.brave.browser&hl=en
   - Clickong on iOS App Store --> https://apps.apple.com/us/app/brave-private-web-browser/id1052879175?mt=8&ign-mpt=uo%3D4

<img width="1096" alt="macOS-English" src="https://user-images.githubusercontent.com/28145373/88560959-c7433480-cffc-11ea-9117-dd766fe5e096.png">
</details>


<details>
<summary>Case 4 - **PASSED** using Win 8.1 x64 - DE</summary>

Browser being used: `Chrome - 84.0.4147.105 (Official Build) (64-bit) (cohort: 84_Win_105)`

 - ensured that staging.brave.com/download looks correct when using `DE`
 - Confirmed "Download Brave for..." Button displayed `Windows 64-bit`
 - Confirmed clicking on the download button correctly downloaded the `exe` file
   - https://brave-browser-downloads.s3.brave.com/latest/BraveBrowserSetup.exe
 - Confirmed clicking on that download button correctly downloaded the `exe` file with `WTS071` appended
   - https://referrals.brave.com/latest/BraveBrowserSetup-WTS071.exe
 - Confirmed direct platform download links (below the main download button) doesn't have referral code appended to the download URL
   - https://referrals.brave.com/latest/BraveBrowserSetup.exe
   - https://referrals.brave.com/latest/BraveBrowserSetup32.exe
   - https://referrals.brave.com/latest/Brave-Browser.pkg
   - https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
   - Clicking on GPS --> https://play.google.com/store/apps/details?id=com.brave.browser&hl=en
   - Clicking on iOS App Store --> https://apps.apple.com/us/app/brave-private-web-browser/id1052879175?mt=8&ign-mpt=uo%3D4

<img width="1261" alt="Screen Shot 2020-07-29 at 12 46 27 AM" src="https://user-images.githubusercontent.com/2602313/88758112-b21df100-d135-11ea-85d4-a28ee171052d.png">
</details>

<details>
<summary>Case 5 - **PASSED** using Win 8.1 x86 - EN</summary>

Browser being used: `MS Edge - 84.0.4147.105 (Official Build) (64-bit)`

 - ensured that staging.brave.com/download looks correct when using `EN`
 - Confirmed "Download Brave for..." Button displayed `Windows 32-bit`
 - Confirmed clicking on the download button correctly downloaded the `exe` file
   - https://brave-browser-downloads.s3.brave.com/latest/BraveBrowserSetup32.exe
 - Confirmed clicking on that download button correctly downloaded the `exe` file with `WTS071` appended
   - https://referrals.brave.com/latest/BraveBrowserSetup32-WTS071.exe
 - Confirmed direct platform download links (below the main download button) doesn't have referral code appended to the download URL
   - https://referrals.brave.com/latest/BraveBrowserSetup.exe
   - https://referrals.brave.com/latest/BraveBrowserSetup32.exe
   - https://referrals.brave.com/latest/Brave-Browser.pkg
   - https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
   - Clicking on GPS --> https://play.google.com/store/apps/details?id=com.brave.browser&hl=en
   - Clicking on iOS App Store --> https://apps.apple.com/us/app/brave-private-web-browser/id1052879175?mt=8&ign-mpt=uo%3D4

<img width="1107" alt="Screen Shot 2020-07-28 at 11 02 30 PM" src="https://user-images.githubusercontent.com/2602313/88751971-cad2da80-d126-11ea-8e96-acfe9f1c64a0.png">
</details>

<details>
<summary>Case 6 - **PASSED** using Win 8.1 x86 - ZH</summary>

Browser being used: `MS Edge - 84.0.4147.105 (Official Build) (64-bit)`

 - ensured that staging.brave.com/download looks correct when using `ZN`
 - Confirmed "Download Brave for..." Button displayed `Windows 32-bit`
 - Confirmed clicking on the download button correctly downloaded the `exe` file
   - https://brave-browser-downloads.s3.brave.com/latest/BraveBrowserSetup32.exe
 - Confirmed clicking on that download button correctly downloaded the `exe` file with `WTS071` appended
   - https://referrals.brave.com/latest/BraveBrowserSetup32-WTS071.exe
 - Confirmed direct platform download links (below the main download button) doesn't have referral code appended to the download URL
   - https://referrals.brave.com/latest/BraveBrowserSetup.exe
   - https://referrals.brave.com/latest/BraveBrowserSetup32.exe
   - https://referrals.brave.com/latest/Brave-Browser.pkg
   - https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
   - Clicking on GPS --> https://play.google.com/store/apps/details?id=com.brave.browser&hl=en
   - Clicking on iOS App Store --> https://apps.apple.com/us/app/brave-private-web-browser/id1052879175?mt=8&ign-mpt=uo%3D4

<img width="1109" alt="Screen Shot 2020-07-28 at 11 08 50 PM" src="https://user-images.githubusercontent.com/2602313/88758210-e5608000-d135-11ea-9666-3bef92d15075.png">
</details>

<details>
<summary>Case 7 - **PASSED** using iPhone 11 iOS 13.6 - EN</summary>

Browser being used: `Safari`

 - ensured that staging.brave.com/download looks correct when using `EN`
 - Confirmed "Download Brave for..." Button displayed `iOS`
 - Confirmed clicking on the download button correctly opens the `App Store` with `Brave Browser` selected
 - Confirmed mobile links directed me to the Brave listing on either Google Play Store or App Store when clicked
   - Clicking on GPS --> https://play.google.com/store/apps/details?id=com.brave.browser&hl=en
   - Clicking on iOS App Store --> https://apps.apple.com/us/app/brave-private-web-browser/id1052879175?mt=8&ign-mpt=uo%3D4

![60598DAB-5BE2-49BF-B7C1-8D135F81936B](https://user-images.githubusercontent.com/2602313/88767235-56f4fa00-d147-11ea-9ecf-4c762839f197.PNG)
</details>

**Comment by kjozwiak** [comment] 2020-07-29 07:17
> Thank you again for this, @LaurenWags!
> 
> > 1. On windows the 64-bit and 32-bit text on the buttons seems a bit bolder than other text on the button.
> 
> Looks like an anti-aliasing problem. I'll have to investigate further, but I think it's slight enough to proceed.

Seems to be looking a lot better compared to the example that @LaurenWags showed via the Slack thread. Example

| Win 10 x64        | Win 10 x86 |
|:-------------:|:-------------:|
|<img width="1494" alt="Screen Shot 2020-07-29 at 3 09 07 AM" src="https://user-images.githubusercontent.com/2602313/88768295-e3ec8300-d148-11ea-9007-548f8e60a46c.png">| <img width="1079" alt="Screen Shot 2020-07-29 at 3 11 40 AM" src="https://user-images.githubusercontent.com/2602313/88768540-3d54b200-d149-11ea-8c88-e27da9cf465e.png">|

| Win 8.1 x64        | Win 8.1 x86 |
|:-------------:|:-------------:|
|<img width="1277" alt="Screen Shot 2020-07-29 at 3 02 19 AM" src="https://user-images.githubusercontent.com/2602313/88767641-f2866a80-d147-11ea-8ba3-eccbe1915a8f.png">| <img width="1107" alt="Screen Shot 2020-07-28 at 11 02 30 PM" src="https://user-images.githubusercontent.com/2602313/88751971-cad2da80-d126-11ea-8e96-acfe9f1c64a0.png">|

> > 1. On a language download page on Win 10 x64, the button incorrectly says 32-bit, it should say 64-bit.
> 
> Found the cause and fixed.

| Win 10 x64        | Win 10 x86 |
|:-------------:|:-------------:|
|<img width="1492" alt="Screen Shot 2020-07-29 at 3 16 10 AM" src="https://user-images.githubusercontent.com/2602313/88769006-e00d3080-d149-11ea-8b07-135df25d4e94.png"> |<img width="1060" alt="Screen Shot 2020-07-29 at 3 13 31 AM" src="https://user-images.githubusercontent.com/2602313/88768772-899ff200-d149-11ea-9cf1-39df75dcaf23.png">|

> > 1. Sometimes translated download pages aren't appending the ref code without a page refresh.
> 
> This should be resolved, but would appreciate confirmation with a few more tests.

Confirmed that this isn't happening anymore 👍 Couldn't reproduce when running through https://github.com/brave/qa-resources/issues/171#issuecomment-665472959.

**Comment by kjozwiak** [comment] 2020-07-29 07:19
@AlanBreck just curious, if no refer is saved/used, should the text links still be pointing to the following?

* https://referrals.brave.com/latest/BraveBrowserSetup.exe
* https://referrals.brave.com/latest/BraveBrowserSetup32.exe
* https://referrals.brave.com/latest/Brave-Browser.pkg

**Comment by AlanBreck** [comment] 2020-07-29 14:01
> @AlanBreck just curious, if no refer is saved/used, should the text links still be pointing to the following?

In the absence of a ref code, brave.com/download currently links to
- https://laptop-updates.brave.com/latest/osx
- https://laptop-updates.brave.com/latest/winx64
- https://laptop-updates.brave.com/latest/winia32
...based on platform. I believe the static page is doing the same. Can you confirm?

@aekeus or @keur can you confirm that the above is correct?

**Comment by keur** [comment] 2020-07-29 15:50
> > @AlanBreck just curious, if no refer is saved/used, should the text links still be pointing to the following?
> 
> In the absence of a ref code, brave.com/download currently links to
> 
> * https://laptop-updates.brave.com/latest/osx
> * https://laptop-updates.brave.com/latest/winx64
> * https://laptop-updates.brave.com/latest/winia32
>   ...based on platform. I believe the static page is doing the same. Can you confirm?
> 
> @aekeus or @keur can you confirm that the above is correct?

This is correct because all of your links redirect to the ones @kjozwiak mentions.

`/latest/osx` => https://referrals.brave.com/latest/Brave-Browser.pkg
`/latest/winia32` => https://referrals.brave.com/latest/BraveBrowserSetup32.exe
`/latest/winx64` => https://referrals.brave.com/latest/BraveBrowserSetup.exe

**Comment by kjozwiak** [comment] 2020-07-30 21:43
Closing this off as we're live on production 👍

**Closed by kjozwiak** 2020-07-30 21:43 UTC
